/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AnalisisDeRend.java
 *
 * Created on 04/12/2009, 10:27:27
 */

package subsistdiscovariaspet;

import java.awt.Color;

/**
 *
 * @author Lea
 */
public class AnalisisDeRend extends javax.swing.JFrame{

    /** Creates new form AnalisisDeRend */
    public AnalisisDeRend() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jDialog1.setTitle("Error");
        jDialog1.setModal(true);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Error en los Parametros");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButton2))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mu");

        jLabel2.setText("Lambda");

        jLabel3.setText("Peticiones \nPendientes");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("40");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("20");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("3");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jTextField2))))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double mu, lambda;
        int i;
        try{
            mu=Integer.parseInt(this.jTextField1.getText());
            lambda=Integer.parseInt(this.jTextField2.getText());
            if(mu>lambda){
                i=Integer.parseInt(this.jTextField3.getText());
                Analisis a = new Analisis(mu,lambda,i);
                this.jTextArea1.setText(a.salida());
                this.listaValores=a.getListaPuntos();
                dibujar();
            }else{
                this.jLabel4.setText("Mu debe ser mayor a Lambda");
                this.jDialog1.setSize(300,180);
                this.jDialog1.setLocation(300,200);
                this.jDialog1.setVisible(true);
            }
        }
        catch(Exception e){
           // javax.swing. // dia=new javax.swing.JDialog();
            this.jLabel4.setText("Error en los parametros");
            this.jDialog1.setSize(300,180);
            this.jDialog1.setLocation(300,200);
            this.jDialog1.setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jDialog1.setVisible(false);
        this.setLocation(300, 200);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisisDeRend().setVisible(true);
            }
        });
    }


    private void dibujar() {

            double XMax=-10000;
            double YMax=-10000;
            for(int i=0;i<this.listaValores.size();i++){
                if(XMax < this.listaValores.get(i)[0])
                    XMax=this.listaValores.get(i)[0];
                if(YMax < this.listaValores.get(i)[1])
                    YMax=this.listaValores.get(i)[1];
            }
            java.awt.Graphics g = jPanel1.getGraphics();
            java.awt.Dimension d = jPanel1.getSize();
            apAncho = d.width;
            apAlto = d.height;
            g.setColor(java.awt.Color.WHITE);
            g.fillRect(0, 0, apAncho, apAlto);
            g.setColor(java.awt.Color.BLACK);
            g.drawRect(0, 0, apAncho-1, apAlto-1);
            xmin = -0.2;
	    xmax = (XMax+0.03);
	    ymin = -0.2;
	    ymax = (YMax+0.03);
            int apCero=(int)( (0-xmin) * (apAncho-1) / (xmax-xmin) );
            int ypCero= (int)( (0-ymin) * (apAlto-1) / (ymax-ymin) );
            ypCero = apAlto - ypCero;
            g.setColor(java.awt.Color.black);
            g.drawLine(0,ypCero,(int)apAncho,ypCero);
            g.drawLine(apCero,apAlto,apCero,0);
            int xp,yp;
           //yp = (int)( (0.5-ymin) * (apAlto-1) / (ymax-ymin) );
            xp=(int)( ( 0.5 - xmin) * (apAncho-1) / (xmax-xmin) );
            g.drawLine(apCero, ypCero, xp, ypCero);
           

           for(int i=0;i<this.listaValores.size();i++){
               double XP;
               XP=this.listaValores.get(i)[0];            
               xp=(int)( (XP - xmin) * (apAncho-1) / (xmax-xmin) );
               yp=(int)ValorY1(i);
               g.setColor(Color.orange);
               g.fillOval(xp, yp, 7, 7);
             
           }
           double XP=0;
           while(XP < XMax){
               xp=(int)( ( XP - xmin) * (apAncho-1) / (xmax-xmin) );
               g.setColor(Color.BLUE);
               String s=""+XP;
               s=s.substring(0,3);
               g.drawString(s,(int)xp,(int)ypCero+10);
               XP +=0.2;
           }
           double YP=0;
           while(YP <YMax){

               g.setColor(Color.BLUE);
               String s=""+YP;
               s=s.substring(0,3);
               g.drawString(s,(int)apCero,(int)ValorY2(YP));
               YP +=0.2;
           }
        }
    private int ValorY1(int valor) {
            double x, y;
            int retorno;
            x = (valor * (xmax - xmin) / (apAncho - 1)) + xmin;
            y=this.listaValores.get(valor)[1];
            retorno = (int) ((y - ymin) * (apAlto - 1) / (ymax - ymin));
            retorno = apAlto - retorno;
            return (retorno);
        }
    private int ValorY2(double valor) {
            double y;
            int retorno;
            y=valor;
            retorno = (int) ((y - ymin) * (apAlto - 1) / (ymax - ymin));
            retorno = apAlto - retorno;
            return (retorno);
        }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
    private int apAlto,apAncho;
    private double xmax,xmin,ymax,ymin;
    private java.util.ArrayList<double[]> listaValores;
}
